- name: Populate Variables
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts['openwrt_board']['board_name'] | replace(',','_') }}.yaml"
        - default.yaml
- name: Revert pending changes
  uci:
    command: revert
- name: Turn off LEDs
  uci:
    command: ensure
    config: system
    type: led
    find_by:
      sysfs: "{{ item.path }}"
    value:
      trigger: none
      default: 0
      name: "{{ item.name }}"
  notify:
    - Restart led
  loop: "{{ leds }}"
- name: Commit pending changes
  uci:
    command: commit
