- name: Populate Variables
  ansible.builtin.include_vars:
    file: "{{ ansible_facts['openwrt_board']['board_name'] }}.yaml"
- name: Revert pending changes
  uci:
    command: revert
- name: Turn off LEDs
  uci:
    command: ensure
    config: system
    type: led
    find_by:
      sysfs: "{{ item.path }}"
    value:
      trigger: none
      default: 0
      name: "{{ item.name }}"
  notify:
    - Restart led
  loop: "{{ leds }}"
- name: Commit pending changes
  uci:
    command: commit
